version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: quiz_postgres
    environment:
      POSTGRES_USER: type
      POSTGRES_PASSWORD: 102030
      POSTGRES_DB: quiz_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: